name: CI

on:
  push:
    branches:
      - feature/newsite  # Change this to your desired branch
  pull_request:
    branches:
      - feature/newsite  # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        run: echo "No build step needed"  # This step is just a placeholder since no build is needed for plain HTML/JS
