name: Deploy to Netlify

on:
  push:
    branches:
      - feature/newsite  # You can change 'feature/newsite' to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Netlify CLI
      run: npm install -g netlify-cli  # Install Netlify CLI

    - name: Deploy to Netlify
      run: |
        netlify deploy --dir=./ --prod  # Deploy the files directly from the root directory
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
